[package]
name = "arc110"
version = "0.1.0"
authors = ["wantjoy"]
edition = "2018"

# dependencies added to new project
[dependencies]
num = "0.3.1"
proconio = "*"

[profile.release]
lto = true
panic = 'abort'
